In [2]:
import torch

### Part 1

Реализуйте при помощи pyTorch функцию, которая возвращает сумму (x.sum()) элементов тензора X, строго превышающих значение limit, которое является входным значением алгоритма.



In [1]:
X = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
limit = int(input())

larger_than_limit_sum = X[X > limit].sum()

print(larger_than_limit_sum)

1
tensor(44)


### Part 2

Реализуйте расчет градиента для функции 
$ f(w) = \prod_{i,j}\ln\ln(w_{i,j}+7) $ в точке $ w = [[5,10],[1,2]] $

In [11]:
w = torch.tensor([[5.,10.],[1.,2.]], requires_grad=True)

function = (w + 7).log().log().prod()
function.backward()

print(w.grad)

tensor([[0.0201, 0.0109],
        [0.0449, 0.0351]])


Реализуйте градиентный спуск для той же функции $ f(w) = \prod_{i,j}\ln\ln(w_{i,j}+7) $ в точке $ w = [[5,10],[1,2]] $

шаг градиентного спуска $ \alpha=0.001 $

Чему будет равен $w^{t=500}$?

In [3]:
# x.data - tensor with requires_grad=False
# gradients are summing -> x.grad.zero_() (inplace)

w = torch.tensor([[5., 10.], [1., 2.]], requires_grad=True)
alpha = 0.001

for _ in range(500):
    # it's critical to calculate function inside the loop:
    function = (w + 7).log().log().prod()
    function.backward()
    w.data -=  alpha * w.grad
    w.grad.zero_()

print(w)

tensor([[4.9900, 9.9948],
        [0.9775, 1.9825]], requires_grad=True)


Перепишите пример, используя torch.optim.SGD

In [5]:
# optimizer.step() performes gradient descend step

w = torch.tensor([[5., 10.], [1., 2.]], requires_grad=True)
alpha = 0.001
optimizer =  torch.optim.SGD([w], lr=alpha)

for _ in range(500):
    # it's critical to calculate function inside the loop:
    function = (w + 7).log().log().prod()
    function.backward()
    optimizer.step()
    optimizer.zero_grad()

print(w)

tensor([[4.9900, 9.9948],
        [0.9775, 1.9825]], requires_grad=True)
